"""add verrifed attribute for user

Revision ID: 086bee01a3a3
Revises: b68520be6e53
Create Date: 2025-10-22 11:19:58.913021

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "086bee01a3a3"
down_revision: str | Sequence[str] | None = "b68520be6e53"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("verified", sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "verified")
    # ### end Alembic commands ###
