"""change password storage size

Revision ID: b68520be6e53
Revises: bf9ced46edd9
Create Date: 2025-10-22 08:39:03.198514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68520be6e53'
down_revision: Union[str, Sequence[str], None] = 'bf9ced46edd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'histories', ['id'])
    op.create_unique_constraint(None, 'ingredients', ['id'])
    op.create_unique_constraint(None, 'pantries', ['id'])
    op.create_unique_constraint(None, 'recipes', ['id'])
    op.create_unique_constraint(None, 'steps', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'steps', type_='unique')
    op.drop_constraint(None, 'recipes', type_='unique')
    op.drop_constraint(None, 'pantries', type_='unique')
    op.drop_constraint(None, 'ingredients', type_='unique')
    op.drop_constraint(None, 'histories', type_='unique')
    # ### end Alembic commands ###
